### ISSUE TITLE
Errors while installing dependencies

### ISSUE THREAD

**Issue by mohsenSy** [Jihad92/arabic-chatbot#1]
Hi, I tried to install the dependencies as described in the readme file but I got these errors:

```
distributed 1.21.8 requires msgpack, which is not installed.
tensorflow 1.6.0 has requirement tensorboard<1.7.0,>=1.6.0, but you'll have tensorboard 1.9.0 which is incompatible.
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I am using `python 3.6.5` and `Ubuntu Desktop 18.04` how can I install the dependencies and make sure the project is up and running correctly?

**Comment by Jihad92** [comment]
Hi. Try using --ignore-installed command option when running pip install. See [this link](https://stackoverflow.com/questions/49932759/pip-10-and-apt-how-to-avoid-cannot-uninstall-x-errors-for-distutils-packages) for more information.
Also, the project was developed using python 3.5.1, so you may use it instead to avoid potential problems.

**Comment by mohsenSy** [comment]
The first error message `distributed 1.21.8 requires msgpack, which is not installed.` was solved by manually installing `msgpack` module.

The third error message `Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.` was solved by following your instructions.

The second one `tensorflow 1.6.0 has requirement tensorboard<1.7.0,>=1.6.0, but you'll have tensorboard 1.9.0 which is incompatible.` remains unsolved until now and it looks like you are deliberately installing the wrong version of `tensorboard`.

**Comment by Jihad92** [comment]
I'll update the dependencies file soon.
The latest version of tensorflow caused some erros, so I stuck with older one.
Please tell if you got the project running.

**Comment by mohsenSy** [comment]
I got it up and running and tested it too :+1:
