### ISSUE TITLE
Include instructions for installing and running in a python virtual environment

### ISSUE THREAD

**Issue by mohsenSy** [Jihad92/arabic-chatbot#2]
It is always preferred to run python code in separate environments to avoid version conflicts between packages.

Add instructions to the README file to create a python virtual environment using [anaconda](https://www.anaconda.com) or [virtualenv](https://virtualenv.pypa.io/en/stable/).

**Comment by Jihad92** [comment]
Yes, it's better to use virtual environments. Will do, thanks (Y)
